package com.dream.model;

import com.dream.db.BaseBean;
import java.io.Serializable;

public class User extends BaseBean implements Serializable {

	/**
	 * @mbggenerated  Sat Nov 14 15:24:36 CST 2015
	 */
	private Integer id;
	/**
	 * @mbggenerated  Sat Nov 14 15:24:36 CST 2015
	 */
	private Integer age;
	/**
	 * @mbggenerated  Sat Nov 14 15:24:36 CST 2015
	 */
	private String userName;
	/**
	 * @mbggenerated  Sat Nov 14 15:24:36 CST 2015
	 */
	private String password;
	/**
	 * @mbggenerated  Sat Nov 14 15:24:36 CST 2015
	 */
	private String realName;
	/**
	 * @mbggenerated  Sat Nov 14 15:24:36 CST 2015
	 */
	private String favourite;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user
	 * @mbggenerated  Sat Nov 14 15:24:36 CST 2015
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
	 * @return  the value of user.id
	 * @mbggenerated  Sat Nov 14 15:24:36 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
	 * @param id  the value for user.id
	 * @mbggenerated  Sat Nov 14 15:24:36 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.age
	 * @return  the value of user.age
	 * @mbggenerated  Sat Nov 14 15:24:36 CST 2015
	 */
	public Integer getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.age
	 * @param age  the value for user.age
	 * @mbggenerated  Sat Nov 14 15:24:36 CST 2015
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.userName
	 * @return  the value of user.userName
	 * @mbggenerated  Sat Nov 14 15:24:36 CST 2015
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.userName
	 * @param userName  the value for user.userName
	 * @mbggenerated  Sat Nov 14 15:24:36 CST 2015
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
	 * @return  the value of user.password
	 * @mbggenerated  Sat Nov 14 15:24:36 CST 2015
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.password
	 * @param password  the value for user.password
	 * @mbggenerated  Sat Nov 14 15:24:36 CST 2015
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.realName
	 * @return  the value of user.realName
	 * @mbggenerated  Sat Nov 14 15:24:36 CST 2015
	 */
	public String getRealName() {
		return realName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.realName
	 * @param realName  the value for user.realName
	 * @mbggenerated  Sat Nov 14 15:24:36 CST 2015
	 */
	public void setRealName(String realName) {
		this.realName = realName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.favourite
	 * @return  the value of user.favourite
	 * @mbggenerated  Sat Nov 14 15:24:36 CST 2015
	 */
	public String getFavourite() {
		return favourite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.favourite
	 * @param favourite  the value for user.favourite
	 * @mbggenerated  Sat Nov 14 15:24:36 CST 2015
	 */
	public void setFavourite(String favourite) {
		this.favourite = favourite;
	}
}