package com.dream.model;

import com.dream.db.BaseBean;
import java.io.Serializable;
import java.util.Date;

public class User extends BaseBean implements Serializable {

	/**
	 * @mbggenerated  Sat Nov 14 22:19:40 CST 2015
	 */
	private Long id;
	/**
	 * @mbggenerated  Sat Nov 14 22:19:40 CST 2015
	 */
	private Integer age;
	/**
	 * 备注: 金币.
	 * @mbggenerated  Sat Nov 14 22:19:40 CST 2015
	 */
	private Integer gold;
	/**
	 * 备注: 梦想积分.
	 * @mbggenerated  Sat Nov 14 22:19:40 CST 2015
	 */
	private Integer score;
	/**
	 * 备注: 用户头像.
	 * @mbggenerated  Sat Nov 14 22:19:40 CST 2015
	 */
	private String headImg;
	/**
	 * @mbggenerated  Sat Nov 14 22:19:40 CST 2015
	 */
	private String userName;
	/**
	 * @mbggenerated  Sat Nov 14 22:19:40 CST 2015
	 */
	private String password;
	/**
	 * @mbggenerated  Sat Nov 14 22:19:40 CST 2015
	 */
	private String realName;
	/**
	 * @mbggenerated  Sat Nov 14 22:19:40 CST 2015
	 */
	private String favourite;
	/**
	 * @mbggenerated  Sat Nov 14 22:19:40 CST 2015
	 */
	private Date createTime;
	/**
	 * @mbggenerated  Sat Nov 14 22:19:40 CST 2015
	 */
	private Date lastUpdateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user
	 * @mbggenerated  Sat Nov 14 22:19:40 CST 2015
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
	 * @return  the value of user.id
	 * @mbggenerated  Sat Nov 14 22:19:40 CST 2015
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
	 * @param id  the value for user.id
	 * @mbggenerated  Sat Nov 14 22:19:40 CST 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.age
	 * @return  the value of user.age
	 * @mbggenerated  Sat Nov 14 22:19:40 CST 2015
	 */
	public Integer getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.age
	 * @param age  the value for user.age
	 * @mbggenerated  Sat Nov 14 22:19:40 CST 2015
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.gold
	 * @return  the value of user.gold
	 * @mbggenerated  Sat Nov 14 22:19:40 CST 2015
	 */
	public Integer getGold() {
		return gold;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.gold
	 * @param gold  the value for user.gold
	 * @mbggenerated  Sat Nov 14 22:19:40 CST 2015
	 */
	public void setGold(Integer gold) {
		this.gold = gold;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.score
	 * @return  the value of user.score
	 * @mbggenerated  Sat Nov 14 22:19:40 CST 2015
	 */
	public Integer getScore() {
		return score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.score
	 * @param score  the value for user.score
	 * @mbggenerated  Sat Nov 14 22:19:40 CST 2015
	 */
	public void setScore(Integer score) {
		this.score = score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.headImg
	 * @return  the value of user.headImg
	 * @mbggenerated  Sat Nov 14 22:19:40 CST 2015
	 */
	public String getHeadImg() {
		return headImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.headImg
	 * @param headImg  the value for user.headImg
	 * @mbggenerated  Sat Nov 14 22:19:40 CST 2015
	 */
	public void setHeadImg(String headImg) {
		this.headImg = headImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.userName
	 * @return  the value of user.userName
	 * @mbggenerated  Sat Nov 14 22:19:40 CST 2015
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.userName
	 * @param userName  the value for user.userName
	 * @mbggenerated  Sat Nov 14 22:19:40 CST 2015
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
	 * @return  the value of user.password
	 * @mbggenerated  Sat Nov 14 22:19:40 CST 2015
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.password
	 * @param password  the value for user.password
	 * @mbggenerated  Sat Nov 14 22:19:40 CST 2015
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.realName
	 * @return  the value of user.realName
	 * @mbggenerated  Sat Nov 14 22:19:40 CST 2015
	 */
	public String getRealName() {
		return realName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.realName
	 * @param realName  the value for user.realName
	 * @mbggenerated  Sat Nov 14 22:19:40 CST 2015
	 */
	public void setRealName(String realName) {
		this.realName = realName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.favourite
	 * @return  the value of user.favourite
	 * @mbggenerated  Sat Nov 14 22:19:40 CST 2015
	 */
	public String getFavourite() {
		return favourite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.favourite
	 * @param favourite  the value for user.favourite
	 * @mbggenerated  Sat Nov 14 22:19:40 CST 2015
	 */
	public void setFavourite(String favourite) {
		this.favourite = favourite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.createTime
	 * @return  the value of user.createTime
	 * @mbggenerated  Sat Nov 14 22:19:40 CST 2015
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.createTime
	 * @param createTime  the value for user.createTime
	 * @mbggenerated  Sat Nov 14 22:19:40 CST 2015
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.lastUpdateTime
	 * @return  the value of user.lastUpdateTime
	 * @mbggenerated  Sat Nov 14 22:19:40 CST 2015
	 */
	public Date getLastUpdateTime() {
		return lastUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.lastUpdateTime
	 * @param lastUpdateTime  the value for user.lastUpdateTime
	 * @mbggenerated  Sat Nov 14 22:19:40 CST 2015
	 */
	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}
}